### ISSUE TITLE
Error in Denrich_mtMut_extr()

### ISSUE THREAD

**Issue by Yujj1123** [shyhihihi/MERCI#3]
Hi, thanks for developing this powerful tool for analyzing mt-transfer! I encountered some issues when attempting to analyze patient su006 from GSE123814, which was analyzed in your article. 

Here is my question：

Read data for su006
```
setwd('BCC/')
merged_mtSNV_table <- NULL
folders <- c('SRR8315754', 'SRR8315755', 'SRR8315756', 'SRR8315757', 'SRR8315758', 'SRR8315759')
for (folder in folders) {
  varFile <- paste0(folder, '/', folder, '.MT_variants.txt')
  mtSNV_table <- MERCI::readMTvar_10x(varFile, minReads=1000)
  if (is.null(merged_mtSNV_table)) {
    merged_mtSNV_table <- mtSNV_table
  } else {
    merged_mtSNV_table <- rbind(merged_mtSNV_table, mtSNV_table)
  }
}
```

Standardize barcodes between original data and MERCI-generated barcodes
```
cell_info <- list.006@meta.data
cell_info$barcode <- rownames(cell_info)
cell_info$MTtransfer <- NA
cell_info$MTtransfer[grepl("T cells", cell_info$celltype)] <- "Donor"
cell_info$MTtransfer[grepl("Tumor", cell_info$celltype)] <- "Receiver"
cell_info <- cell_info[,colnames(cell_info) %in% c('celltype','barcode','MTtransfer')]
cell_info$id <- sub(".*_(.*)", "\\1-1", cell_info$barcode) 

T_cells <- cell_info$id[cell_info$celltype=='T cells']  
Cancer_cells <- cell_info$id[cell_info$celltype=='Tumor']  

```
Use previously merged Coverage_Cell.csv for su006
```
CoverFile <- 'su006.Coverage_Cell.csv'  
selected_Cells <- c(T_cells, Cancer_cells)  
MTcoverage_inf <- readCoverage_10x(CoverFile)
MTcoverage_inf <- MTcoverage_inf[,colnames(MTcoverage_inf) %in% selected_Cells]

s.mtSNV_table <- merged_mtSNV_table[merged_mtSNV_table$Cell%in%selected_Cells, ]  
mtSNV_ma <- MTmutMatrix_transform(MT_variants=s.mtSNV_table, MT_coverage=MTcoverage_inf, donor_cells=T_cells, mixed_cells=Cancer_cells, min_d=5, min_observeRate= 0.1)   
```

Encounter error in Denrich_mtMut_extr()
```
s.muts <- Denrich_mtMut_extr(varMatrix=mtSNV_ma, donor_cells=T_cells, mixed_cells=Cancer_cells, OR=2, Nmut_min=2)

Error in FUN(newX[, i], ...) : 
  'list' object cannot be coerced to type 'double'`
```

I carefully checked the data structure of ‘mtSNV_ma’ and found that all elements are of type 'list', with some elements containing two numeric values.

`str(mtSNV_ma[31, 1215])
List of 1
 $ : num [1:2] 0.00667 0.00599`

I'm stuck at this point and would be grateful for your assistance. I'm eagerly awaiting your response. Thank you very much!

**Comment by shyhihihi** [comment]
Dear user,

Since we do not know what your embedded data looks like, I have no idea why the data type of the R object 'mtSNV_ma' was not correct in your analysis.

It is notable that the patient su006 in GSE123814  suffered two different treatment, we only focused on the treatment naive group (see below).
   Run                 donor   cell_type         source_name                       Treatment    
1 SRR8315754   su006   CD45+ CD3-   Basal cell carinoma tumor   pre              
2 SRR8315755   su006   CD45+ CD3+  Basal cell carinoma tumor   pre              
3 SRR8315756   su006   CD45- CD3-    Basal cell carinoma tumor   pre              
4 SRR8315778   su006  CD45+ CD3+   Basal cell carinoma tumor   pre   

'SRR8315757', 'SRR8315758', 'SRR8315759' belongs to the samples of su006 post ICB treatment. Since we are not sure if ICB treatment will influence MT transfer activity, we do not consider these libraries.

Here I attached our code for your reference (I have tested it, there is no errors reported):
libray(MERCI)
load(./'BCC_HC_bcc.su006.pre.RData') ;
Cancer_cells <- rownames(cell_info)[cell_info$label=='TM_cells'] ;
T_cells  <- rownames(cell_info)[cell_info$label=='Tcell'] ;
mtSNV_table <- MTvar_Hcover[MTvar_Hcover$Cell_reads > 1000,] ;

Cancer_cells <- intersect(Cancer_cells, mtSNV_table$Cell) ;
T_cells <- intersect(T_cells, mtSNV_table$Cell) ;

selected_Cells <- c(T_cells, Cancer_cells)  
MTcoverage_inf <- MT_coverage[, colnames(MT_coverage)%in%selected_Cells] ;


s.mtSNV_table <- mtSNV_table[mtSNV_table$Cell%in%selected_Cells, ] 
mtSNV_ma <- MTmutMatrix_transform(MT_variants=s.mtSNV_table, MT_coverage=MTcoverage_inf, donor_cells=T_cells, mixed_cells=Cancer_cells, min_d=5, min_observeRate= 0.1)   

s.muts <- Denrich_mtMut_extr(varMatrix=mtSNV_ma, donor_cells=T_cells, mixed_cells=Cancer_cells, OR=2, Nmut_min=2)
DNA_rank <- Cell_Neff_cal(varMatrix=mtSNV_ma, MT_variants=s.mtSNV_table, MT_coverage=MTcoverage_inf, donor_cells=T_cells, mixed_cells=Cancer_cells, mutFeatures=s.muts, adjust=FALSE)

cell_exp <- cell_exp[, selected_Cells]  ;
RNA_rank <- MERCI_LOO_MT_est(cell_exp, reciever_cells=Cancer_cells, donor_cells=T_cells, organism='Human')  

CellN_stat <- CellNumber_test(DNA_rank, RNA_rank, Number_R=1000)
MTreceiver_pre <- MERCI_ReceiverPre(DNA_rank, RNA_rank, top_rank=50)

If you are still unable to figure out the problem, you can send me your intermediate  R data (such as 'T_cells', 'Cancer_cells', 'MTcoverage_inf' and 's.mtSNV_table' ) and I will help double-check them when I am available. (zhangh12@chop.edu)

Thanks!

**Comment by Yujj1123** [comment]
Thanks Hongyi
