### ISSUE TITLE
FileNotFoundError: [Errno 2] *.MT.bam`: No such file or directory

### ISSUE THREAD

**Issue by FLY-Fiancee** [shyhihihi/MERCI#5]
Hi,

When I running:
`python ./soft/MERCI-main/MERCI-mtSNP.py -D 10x_scRNA-seq \
-o /home/fbio/Documents/mouse/X/output  \
-S X \
-b /home/fbio/Documents/mouse/X/outs/possorted_genome_bam.bam  \
-f /home/fbio/Documents/refdata-gex-mm10-2020-A/fasta/genome.fa  \
-c /home/fbio/Documents/mouse/X/outs/filtered_feature_bc_matrix`
I got the error message:
FileNotFoundError: [Errno 2] could not open alignment file `/home/fbio/Documents/mouse/X/output/X.MT.bam`: No such file or directory

Would you give me any suggestions?

**Comment by lattaai7** [comment]
Hello, I tried to solve the issue.

This is what I did:

Add a function to create the output directory if it doesn't exist, and call this function before writing any files. This should resolve the FileNotFoundError.

You can review changes in this commit: https://github.com/lattaai7/shyhihihi-MERCI-5/commit/97069060f15c8fe9f98c283fcf5c8c297a6b5d69.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by FLY-Fiancee** [comment]
I checked my reference genome, already cellranger generated barcorde, and I confirmed that there is the presence of mt related genes and chrM, so I wasn't able to find the reason for this problem. When I was looking at the code in MERCI-mtSNP.py, I observed that lines 55line to 77 are a write out of that file (X.MT.bam) file, but I don't know why this is a problem?

**Comment by GlenZhang-GZ** [comment]
Hi, I met the same question. Did you solve it? If so, could you tell me how to solve it? Thanks.

**Comment by shyhihihi** [comment]
This is unusual because the .MT.bam file should be automatically generated in the user-defined output folder (specified using the -o parameter). Have you successfully troubleshot the issue?

**Comment by GlenZhang-GZ** [comment]
> This is unusual because the .MT.bam file should be automatically generated in the user-defined output folder (specified using the -o parameter). Have you successfully troubleshot the issue?

Thanks! I solved it !
